[workspace]
members = ["http", "database", "core", "support"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Mimi"]
description = "Vault system SAAS"
documentation = "https://example.com/bar"


[workspace.dependencies]
rstest = "0.23.0"