[package]
name = "core"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]


[dev-dependencies]
rstest.workspace = true