[package]
name = "database"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
support = { path = "../support" }
mockall.workspace = true

[dev-dependencies]
rstest.workspace = true
